services:
  mysql:
    image: mysql:8.0
    container_name: economy_quiz_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: economy_quiz
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: quiz_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "quiz_user", "-pquiz_password"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  api:
    build: .
    container_name: economy_quiz_api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: quiz_user
      DB_PASSWORD: quiz_password
      DB_NAME: economy_quiz
      API_HOST: 0.0.0.0
      API_PORT: 8000
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mysql_data:
